name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t sgutnikov108/python-web-server .

      # Test the Docker image
      - name: Test Docker Image
        run: docker run -d -p 80:80 sgutnikov108/python-web-server && sleep 5 && curl -f http://localhost:80

  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Scan Docker Image for Vulnerabilities
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@v0.10.0
        with:
          image-ref: sgutnikov108/python-web-server

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]

    steps:
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker tag sgutnikov108/python-web-server:latest sgutnikov108/python-web-server:latest
          docker push sgutnikov108/python-web-server:latest

      # Deploy to Production (Example using SSH)
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          password: ${{ secrets.PROD_SERVER_PASSWORD }}
          script: |
            docker pull sgutnikov108/python-web-server:latest
            docker stop web_app || true
            docker rm web_app || true
            docker run -d --name web_app -p 80:80 sgutnikov108/python-web-server:latest
