name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t python-web-server .

      - name: Test Docker image
        run: docker run -d -p 80:80 python-web-server && sleep 5 && curl -f http://localhost:80

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag python-web-server:latest <your-dockerhub-username>/python-web-server:latest
          docker push sgutnikov108/python-web-server:latest
